### ISSUE TITLE
No issue, just wanting to say hi.  "Way Cool !! , another vz emulator"

### ISSUE THREAD

**Issue by bushy555** [PaulAnderson/VzEmulator#7]
Hi Paul,

Have just discovered your emulator. To my calculations, yours makes about the 14th for the VZ for various platforms.
Would love for you to join up our VZ facebook group. There's only a few of us active people still floating about, and we seem to all lurk/hang out on this group. We had a yahoo mailing list for twenty years, but its now pretty much dead once Yahoo killed off files and photos.

Facebook : search "VZ200 VZ300 Laser210 Laser310 fans"

Have posted it up, and already one member has compiled your source for interest.

Cheers
Dave

**Comment by PaulAnderson** [comment]
Hey Dave,

Thanks for dropping in, I had no idea anyone else was still interested in this! I've seen a few a few of the other emulators around and wanted to create my own as a learning exercise and to be able to add new features.

Pity Yahoo killed everything off!. I'll check out the facebook group.

Cheers
Paul

**Comment by bushy555** [comment]
Hi Paul,

Yes, please check our page --- three or four other emulator writers are within the ‘hang out’ people on this page.  We would be more than greatful to have another VZ enthusiast on board, and, no doubt, we would love to see your emulator grow into something wonderful.
Out of the 140 peeps on the group, there are perhaps only 40 or so that are reasonably “active”.  Some peeps on the group are hardware enthusiasts and others other software --- myself being right into graphics and sounds “old school demos” for example. Half of the graphical and 1 bit audio demos that are on youtube are my trial and error creations.
I have so many unfinished projects unfortunately – I see something else “Oh, shiney thing” , and move on. I started ‘Lode Runner’ in C and then moved the animation over to asm --- and got distracted.
Currently I have embarked on the massive project that no one has ever touched in the past 20 years – to collect all known VZ software titles, and to place them all into one large depositry.

Check out Andrews page if you haven’t already done so:
www.vz200.org<http://www.vz200.org>
www.vz200.org/bushy<http://www.vz200.org/bushy> is my little ‘everything vz’


Jonathon Cauldwell (UK) created a Multi Platform Arcade game designer, which uses a simplified basic type language, and can compile this to different platforms. The VZ is one, and a fellow by the name of Kees has done a terrific job on porting a bunch of games – admittedly most only work in the VZ’s super “hacked” resolution of 256x192.   https://jonathan-cauldwell.itch.io/multi-platform-arcade-game-designer

Cheers,
Dave




Hey Dave,

Thanks for dropping in, I had no idea anyone else was still interested in this! I've seen a few a few of the other emulators around and wanted to create my own as a learning exercise and to be able to add new features.

Pity Yahoo killed everything off!. I'll check out the facebook group.

Cheers
Paul
